import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import { Sidebar } from "lucide-react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({ children }) {
  return (
    <main className="relative">
        <Navbar />
        <div className="flex">
          <section className="max-w-3xl mx-auto p-4 m-12">
            <div className="w-full">{children}</div>
          </section>
        </div>
      </main>
  );
}
