import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({ children }) {
  return (
    <main className="max-w-6xl mx-auto p-4">
        <Navbar />
        <div className="flex">
          <section className="w-full">
            <div className="mt-8">{children}</div>
          </section>
        </div>
      </main>
  );
}
